### ISSUE TITLE
Upgrade achives  to latest version

### ISSUE THREAD

**Issue by rricharz** [pi-top/pi-topSPEAKER#5]
Using the latest Raspbian Stretch image (2017-09-07)  the commands
 
sudo apt-get update

sudo apt-get upgrade

sudo apt install pt-speaker

still installs pt-peripheral-cfg

**Comment by m-roberts** [comment]
Hi Rene - we are very close to releasing this to RPi - we just wanted to make sure that things were documented adequately before doing so! We will be pushing this up to them shortly :) They usually go live within 24 hours
